version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        # command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        # Uncomment these lines to persist data on the local filesystem.
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata

    webserver:
        image: docker-airflow:1.10.8
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - HOST_HOME=$HOST_HOME
            - MONGODB_HOST=$MONGODB_HOST
            - MONGODB_BACKUP=$MONGODB_BACKUP
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
            - AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__VISIBILITY_TIMEOUT=36000 
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./script_python:/usr/local/airflow/script_python
            - /var/run/docker.sock:/var/run/docker.sock
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        group_add:
            - ${DOCKER_GROUP}
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: docker-airflow:1.10.8
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: docker-airflow:1.10.8
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - MONGODB_HOST=$MONGODB_HOST
            - MONGODB_BACKUP=$MONGODB_BACKUP
            - AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__VISIBILITY_TIMEOUT=36000 
            - PYTHONPATH=/usr/local/airflow
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        image: docker-airflow:1.10.8
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./script_python:/usr/local/airflow/script_python
            - /var/run/docker.sock:/var/run/docker.sock
            - $MONGODB_BACKUP:/usr/local/airflow/mongodb_backup
            - /usr/bin:/usr/local/airflow/bin
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        group_add:
            - ${DOCKER_GROUP}
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - HOST_HOME=$HOST_HOME
            - MONGODB_HOST=$MONGODB_HOST
            - MONGODB_BACKUP=$MONGODB_BACKUP
            - SLACK_API_TOKEN=$SLACK_API_TOKEN
            - BINANCE_API=$BINANCE_API
            - BINANCE_SECRET=$BINANCE_SECRET
            - TRADIER_TOKEN=$TRADIER_TOKEN
            - TRADIER_TOKEN2=$TRADIER_TOKEN2
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
            - AIRFLOW__CELERY_BROKER_TRANSPORT_OPTIONS__VISIBILITY_TIMEOUT=36000 
            - PYTHONPATH=/usr/local/airflow
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker
